//! WebRTC offer/answer and ICE candidate negotiation primitives.
//!
//! This module stops at SDP/candidate generation and application. It does not
//! claim that a direct ICE route, data channel, relay, or media plane is active;
//! later Phase-G/J goals select routes and move application text/audio frames.

use crate::{
    Endpoint, IceServerConfig, TransportError, TransportSession, TransportSessionSnapshot,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::sync::Arc;
use tokio::sync::Mutex;
use webrtc::peer_connection::{
    register_default_interceptors, MediaEngine, PeerConnection, PeerConnectionBuilder,
    PeerConnectionEventHandler, RTCConfigurationBuilder, RTCIceCandidateInit,
    RTCIceConnectionState, RTCIceGatheringState, RTCIceServer, RTCPeerConnectionState, RTCSdpType,
    RTCSessionDescription, Registry,
};

/// SDP type carried through signaling.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebRtcSdpType {
    /// SDP offer.
    Offer,
    /// SDP answer.
    Answer,
}

/// Serializable WebRTC session description for opaque signaling payloads.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcSessionDescription {
    /// Offer or answer.
    pub sdp_type: WebRtcSdpType,
    /// SDP body generated by the WebRTC stack.
    pub sdp: String,
}

impl fmt::Debug for WebRtcSessionDescription {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WebRtcSessionDescription")
            .field("sdp_type", &self.sdp_type)
            .field("sdp", &"<redacted>")
            .finish()
    }
}

/// Serializable ICE candidate for trickle signaling.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcIceCandidate {
    /// Candidate attribute line.
    pub candidate: String,
    /// SDP media id, when supplied by the WebRTC stack.
    #[serde(default)]
    pub sdp_mid: Option<String>,
    /// SDP media line index, when supplied by the WebRTC stack.
    #[serde(default)]
    pub sdp_mline_index: Option<u16>,
    /// ICE username fragment, when supplied by the WebRTC stack.
    #[serde(default)]
    pub username_fragment: Option<String>,
}

impl fmt::Debug for WebRtcIceCandidate {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WebRtcIceCandidate")
            .field("candidate", &"<redacted>")
            .field("sdp_mid", &self.sdp_mid)
            .field("sdp_mline_index", &self.sdp_mline_index)
            .field(
                "username_fragment",
                &self.username_fragment.as_ref().map(|_| "<redacted>"),
            )
            .finish()
    }
}

/// Encrypted negotiation payload kind carried as opaque signaling bytes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebRtcNegotiationPayloadKind {
    /// Sealed SDP offer.
    Offer,
    /// Sealed SDP answer.
    Answer,
    /// Sealed trickled ICE candidate.
    Candidate,
}

/// AES-GCM sealed WebRTC negotiation payload safe to hand to the signaling service.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
pub struct SealedWebRtcNegotiationPayload {
    /// Wire format version.
    pub version: u8,
    /// Payload kind used as authenticated context.
    pub kind: WebRtcNegotiationPayloadKind,
    /// 96-bit AES-GCM nonce.
    pub nonce: [u8; 12],
    /// Ciphertext plus authentication tag.
    pub ciphertext: Vec<u8>,
}

impl fmt::Debug for SealedWebRtcNegotiationPayload {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SealedWebRtcNegotiationPayload")
            .field("version", &self.version)
            .field("kind", &self.kind)
            .field("nonce", &"<redacted>")
            .field(
                "ciphertext",
                &format_args!("{} bytes", self.ciphertext.len()),
            )
            .finish()
    }
}

impl SealedWebRtcNegotiationPayload {
    /// Serialize sealed payload bytes for `SignalingClient::publish_signal`.
    pub fn to_opaque_bytes(&self) -> Result<Vec<u8>, TransportError> {
        serde_json::to_vec(self).map_err(|err| {
            TransportError::Unavailable(format!("encode sealed negotiation payload failed: {err}"))
        })
    }

    /// Decode sealed payload bytes returned by `SignalingClient::take_signals`.
    pub fn from_opaque_bytes(bytes: &[u8]) -> Result<Self, TransportError> {
        serde_json::from_slice(bytes).map_err(|err| {
            TransportError::Unavailable(format!("decode sealed negotiation payload failed: {err}"))
        })
    }
}

/// Symmetric sealer for WebRTC negotiation payloads before they enter signaling.
pub struct WebRtcNegotiationSealer {
    key: [u8; 32],
}

impl fmt::Debug for WebRtcNegotiationSealer {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WebRtcNegotiationSealer")
            .field("key", &"<redacted>")
            .finish()
    }
}

impl WebRtcNegotiationSealer {
    /// Construct a sealer from a caller-supplied 256-bit room/session negotiation key.
    #[must_use]
    pub fn new(key: [u8; 32]) -> Self {
        Self { key }
    }

    /// Seal an SDP offer or answer.
    pub fn seal_description(
        &self,
        description: &WebRtcSessionDescription,
    ) -> Result<SealedWebRtcNegotiationPayload, TransportError> {
        let kind = match description.sdp_type {
            WebRtcSdpType::Offer => WebRtcNegotiationPayloadKind::Offer,
            WebRtcSdpType::Answer => WebRtcNegotiationPayloadKind::Answer,
        };
        self.seal_json(kind, description)
    }

    /// Open a sealed SDP offer or answer.
    pub fn open_description(
        &self,
        sealed: &SealedWebRtcNegotiationPayload,
    ) -> Result<WebRtcSessionDescription, TransportError> {
        match sealed.kind {
            WebRtcNegotiationPayloadKind::Offer | WebRtcNegotiationPayloadKind::Answer => {
                self.open_json(sealed)
            }
            WebRtcNegotiationPayloadKind::Candidate => Err(TransportError::Unavailable(
                "sealed candidate cannot be opened as SDP".to_owned(),
            )),
        }
    }

    /// Seal one trickled ICE candidate.
    pub fn seal_candidate(
        &self,
        candidate: &WebRtcIceCandidate,
    ) -> Result<SealedWebRtcNegotiationPayload, TransportError> {
        self.seal_json(WebRtcNegotiationPayloadKind::Candidate, candidate)
    }

    /// Open one sealed trickled ICE candidate.
    pub fn open_candidate(
        &self,
        sealed: &SealedWebRtcNegotiationPayload,
    ) -> Result<WebRtcIceCandidate, TransportError> {
        if sealed.kind != WebRtcNegotiationPayloadKind::Candidate {
            return Err(TransportError::Unavailable(
                "sealed SDP cannot be opened as candidate".to_owned(),
            ));
        }
        self.open_json(sealed)
    }

    fn seal_json<T: Serialize>(
        &self,
        kind: WebRtcNegotiationPayloadKind,
        value: &T,
    ) -> Result<SealedWebRtcNegotiationPayload, TransportError> {
        use aes_gcm::aead::{Aead, Payload};
        use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
        use rand::RngCore;

        let mut nonce = [0u8; 12];
        rand::rngs::OsRng.fill_bytes(&mut nonce);
        let plaintext = serde_json::to_vec(value).map_err(|err| {
            TransportError::Unavailable(format!("encode negotiation payload failed: {err}"))
        })?;
        let cipher = Aes256Gcm::new_from_slice(&self.key).map_err(|err| {
            TransportError::Unavailable(format!("initialize negotiation sealer failed: {err}"))
        })?;
        let ciphertext = cipher
            .encrypt(
                Nonce::from_slice(&nonce),
                Payload {
                    msg: &plaintext,
                    aad: aad_for_kind(kind).as_bytes(),
                },
            )
            .map_err(|err| {
                TransportError::Unavailable(format!("seal negotiation payload failed: {err}"))
            })?;
        Ok(SealedWebRtcNegotiationPayload {
            version: 1,
            kind,
            nonce,
            ciphertext,
        })
    }

    fn open_json<T: for<'de> Deserialize<'de>>(
        &self,
        sealed: &SealedWebRtcNegotiationPayload,
    ) -> Result<T, TransportError> {
        use aes_gcm::aead::{Aead, Payload};
        use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
        if sealed.version != 1 {
            return Err(TransportError::Unavailable(
                "unsupported sealed negotiation payload version".to_owned(),
            ));
        }
        let cipher = Aes256Gcm::new_from_slice(&self.key).map_err(|err| {
            TransportError::Unavailable(format!("initialize negotiation opener failed: {err}"))
        })?;
        let plaintext = cipher
            .decrypt(
                Nonce::from_slice(&sealed.nonce),
                Payload {
                    msg: &sealed.ciphertext,
                    aad: aad_for_kind(sealed.kind).as_bytes(),
                },
            )
            .map_err(|err| {
                TransportError::Unavailable(format!("open negotiation payload failed: {err}"))
            })?;
        serde_json::from_slice(&plaintext).map_err(|err| {
            TransportError::Unavailable(format!("decode negotiation payload failed: {err}"))
        })
    }
}

fn aad_for_kind(kind: WebRtcNegotiationPayloadKind) -> &'static str {
    match kind {
        WebRtcNegotiationPayloadKind::Offer => "discrypt-webrtc-negotiation-v1:offer",
        WebRtcNegotiationPayloadKind::Answer => "discrypt-webrtc-negotiation-v1:answer",
        WebRtcNegotiationPayloadKind::Candidate => "discrypt-webrtc-negotiation-v1:candidate",
    }
}

/// Direct ICE/WebRTC state and metrics visible to app-service adapters.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcDirectPathMetrics {
    /// Snapshot schema version for app-service/Tauri consumers.
    pub schema_version: u16,
    /// Current aggregate peer connection state.
    pub peer_connection_state: String,
    /// Current ICE connection state.
    pub ice_connection_state: String,
    /// Current ICE gathering state.
    pub ice_gathering_state: String,
    /// Total local candidates gathered by the WebRTC stack.
    pub local_candidates_gathered: u64,
    /// Total remote trickle candidates applied to this peer.
    pub remote_candidates_applied: u64,
    /// True only when WebRTC reports a direct ICE-capable connected/completed state.
    pub direct_path_ready: bool,
}

impl WebRtcDirectPathMetrics {
    /// Current metrics schema.
    pub const SCHEMA_VERSION: u16 = 1;
}

#[derive(Clone, Debug)]
struct DirectPathMetricsState {
    peer_connection_state: RTCPeerConnectionState,
    ice_connection_state: RTCIceConnectionState,
    ice_gathering_state: RTCIceGatheringState,
    local_candidates_gathered: u64,
    remote_candidates_applied: u64,
}

impl Default for DirectPathMetricsState {
    fn default() -> Self {
        Self {
            peer_connection_state: RTCPeerConnectionState::New,
            ice_connection_state: RTCIceConnectionState::New,
            ice_gathering_state: RTCIceGatheringState::New,
            local_candidates_gathered: 0,
            remote_candidates_applied: 0,
        }
    }
}

impl DirectPathMetricsState {
    fn snapshot(&self) -> WebRtcDirectPathMetrics {
        WebRtcDirectPathMetrics {
            schema_version: WebRtcDirectPathMetrics::SCHEMA_VERSION,
            peer_connection_state: self.peer_connection_state.to_string(),
            ice_connection_state: self.ice_connection_state.to_string(),
            ice_gathering_state: self.ice_gathering_state.to_string(),
            local_candidates_gathered: self.local_candidates_gathered,
            remote_candidates_applied: self.remote_candidates_applied,
            direct_path_ready: matches!(
                self.peer_connection_state,
                RTCPeerConnectionState::Connected
            ) || matches!(
                self.ice_connection_state,
                RTCIceConnectionState::Connected | RTCIceConnectionState::Completed
            ),
        }
    }
}

/// Local WebRTC negotiation configuration.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcNegotiationConfig {
    /// Validated STUN/TURN configuration from invite/group policy.
    pub ice_servers: IceServerConfig,
    /// Local UDP bind addresses. Use `127.0.0.1:0` in deterministic tests.
    pub udp_addrs: Vec<String>,
    /// DataChannel label used to ensure SDP negotiates an application m-line.
    pub data_channel_label: String,
}

impl WebRtcNegotiationConfig {
    /// Build a config with a safe loopback bind default for tests/local embedded use.
    #[must_use]
    pub fn new(ice_servers: IceServerConfig) -> Self {
        Self {
            ice_servers,
            udp_addrs: vec!["127.0.0.1:0".to_owned()],
            data_channel_label: "discrypt-control".to_owned(),
        }
    }

    fn validate(&self, now: DateTime<Utc>) -> Result<(), TransportError> {
        self.ice_servers.validate_credentials_at(now)?;
        if self.udp_addrs.is_empty() {
            return Err(TransportError::Unavailable(
                "at least one UDP bind address is required for WebRTC negotiation".to_owned(),
            ));
        }
        if self.data_channel_label.trim().is_empty() {
            return Err(TransportError::Unavailable(
                "data channel label is required for WebRTC negotiation".to_owned(),
            ));
        }
        Ok(())
    }
}

/// WebRTC negotiation owner for one peer connection.
pub struct WebRtcNegotiator {
    peer_connection: Box<dyn PeerConnection>,
    candidates: Arc<Mutex<Vec<WebRtcIceCandidate>>>,
    metrics: Arc<Mutex<DirectPathMetricsState>>,
    data_channel_label: String,
}

impl WebRtcNegotiator {
    /// Create a WebRTC peer connection configured with validated ICE servers.
    pub async fn new(config: WebRtcNegotiationConfig) -> Result<Self, TransportError> {
        config.validate(Utc::now())?;
        let candidates = Arc::new(Mutex::new(Vec::new()));
        let metrics = Arc::new(Mutex::new(DirectPathMetricsState::default()));
        let handler = Arc::new(CandidateCollector {
            candidates: Arc::clone(&candidates),
            metrics: Arc::clone(&metrics),
        });
        let mut media = MediaEngine::default();
        media.register_default_codecs().map_err(|err| {
            TransportError::Unavailable(format!("register media codecs failed: {err}"))
        })?;
        let registry =
            register_default_interceptors(Registry::new(), &mut media).map_err(|err| {
                TransportError::Unavailable(format!("register WebRTC interceptors failed: {err}"))
            })?;
        let peer_connection = PeerConnectionBuilder::new()
            .with_configuration(
                RTCConfigurationBuilder::new()
                    .with_ice_servers(to_rtc_ice_servers(&config.ice_servers))
                    .build(),
            )
            .with_media_engine(media)
            .with_interceptor_registry(registry)
            .with_handler(handler)
            .with_udp_addrs(config.udp_addrs.clone())
            .build()
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("build WebRTC peer failed: {err}"))
            })?;
        Ok(Self {
            peer_connection: Box::new(peer_connection),
            candidates,
            metrics,
            data_channel_label: config.data_channel_label,
        })
    }

    /// Create and set a local SDP offer. Candidate gathering starts after this call.
    pub async fn create_offer(&self) -> Result<WebRtcSessionDescription, TransportError> {
        let _channel = self
            .peer_connection
            .create_data_channel(&self.data_channel_label, None)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("create data channel failed: {err}"))
            })?;
        let offer = self
            .peer_connection
            .create_offer(None)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("create WebRTC offer failed: {err}"))
            })?;
        self.peer_connection
            .set_local_description(offer)
            .await
            .map_err(|err| TransportError::Unavailable(format!("set local offer failed: {err}")))?;
        let local = self
            .peer_connection
            .local_description()
            .await
            .ok_or_else(|| {
                TransportError::Unavailable("WebRTC local offer was not recorded".to_owned())
            })?;
        WebRtcSessionDescription::from_rtc(local)
    }

    /// Apply a remote offer, then create and set a local SDP answer.
    pub async fn create_answer(
        &self,
        remote_offer: WebRtcSessionDescription,
    ) -> Result<WebRtcSessionDescription, TransportError> {
        self.peer_connection
            .set_remote_description(remote_offer.into_rtc()?)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("set remote offer failed: {err}"))
            })?;
        let answer = self
            .peer_connection
            .create_answer(None)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("create WebRTC answer failed: {err}"))
            })?;
        self.peer_connection
            .set_local_description(answer)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("set local answer failed: {err}"))
            })?;
        let local = self
            .peer_connection
            .local_description()
            .await
            .ok_or_else(|| {
                TransportError::Unavailable("WebRTC local answer was not recorded".to_owned())
            })?;
        WebRtcSessionDescription::from_rtc(local)
    }

    /// Apply a remote answer to an offer-side peer connection.
    pub async fn accept_answer(
        &self,
        remote_answer: WebRtcSessionDescription,
    ) -> Result<(), TransportError> {
        self.peer_connection
            .set_remote_description(remote_answer.into_rtc()?)
            .await
            .map_err(|err| TransportError::Unavailable(format!("set remote answer failed: {err}")))
    }

    /// Apply one trickled remote ICE candidate.
    pub async fn add_remote_candidate(
        &self,
        candidate: WebRtcIceCandidate,
    ) -> Result<(), TransportError> {
        self.peer_connection
            .add_ice_candidate(candidate.into_rtc())
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("add ICE candidate failed: {err}"))
            })?;
        self.metrics.lock().await.remote_candidates_applied += 1;
        Ok(())
    }

    /// Drain locally gathered ICE candidates in callback order for signaling.
    pub async fn drain_local_candidates(&self) -> Vec<WebRtcIceCandidate> {
        let mut candidates = self.candidates.lock().await;
        std::mem::take(&mut *candidates)
    }

    /// Current direct ICE/WebRTC metrics for app-service/Tauri state surfaces.
    pub async fn direct_path_metrics(&self) -> WebRtcDirectPathMetrics {
        self.metrics.lock().await.snapshot()
    }

    /// Select a direct route in a transport session only after WebRTC reports readiness.
    pub async fn select_direct_route_if_ready(
        &self,
        session: &mut TransportSession,
        endpoint: Endpoint,
    ) -> Result<Option<TransportSessionSnapshot>, TransportError> {
        if !self.direct_path_metrics().await.direct_path_ready {
            return Ok(None);
        }
        session
            .select_direct(endpoint)
            .map(Some)
            .map_err(Into::into)
    }

    /// Close the peer connection.
    pub async fn close(&self) -> Result<(), TransportError> {
        self.peer_connection
            .close()
            .await
            .map_err(|err| TransportError::Unavailable(format!("close WebRTC peer failed: {err}")))
    }
}

impl WebRtcSessionDescription {
    fn from_rtc(description: RTCSessionDescription) -> Result<Self, TransportError> {
        let sdp_type = match description.sdp_type {
            RTCSdpType::Offer => WebRtcSdpType::Offer,
            RTCSdpType::Answer => WebRtcSdpType::Answer,
            other => {
                return Err(TransportError::Unavailable(format!(
                    "unsupported SDP type for Discrypt negotiation: {other:?}"
                )));
            }
        };
        Ok(Self {
            sdp_type,
            sdp: description.sdp,
        })
    }

    fn into_rtc(self) -> Result<RTCSessionDescription, TransportError> {
        let rtc = match self.sdp_type {
            WebRtcSdpType::Offer => RTCSessionDescription::offer(self.sdp),
            WebRtcSdpType::Answer => RTCSessionDescription::answer(self.sdp),
        }
        .map_err(|err| TransportError::Unavailable(format!("parse remote SDP failed: {err}")))?;
        Ok(rtc)
    }
}

impl WebRtcIceCandidate {
    fn into_rtc(self) -> RTCIceCandidateInit {
        RTCIceCandidateInit {
            candidate: self.candidate,
            sdp_mid: self.sdp_mid,
            sdp_mline_index: self.sdp_mline_index,
            username_fragment: self.username_fragment,
            url: None,
        }
    }
}

#[derive(Clone)]
struct CandidateCollector {
    candidates: Arc<Mutex<Vec<WebRtcIceCandidate>>>,
    metrics: Arc<Mutex<DirectPathMetricsState>>,
}

#[async_trait::async_trait]
impl PeerConnectionEventHandler for CandidateCollector {
    async fn on_ice_gathering_state_change(&self, state: RTCIceGatheringState) {
        self.metrics.lock().await.ice_gathering_state = state;
    }

    async fn on_ice_connection_state_change(&self, state: RTCIceConnectionState) {
        self.metrics.lock().await.ice_connection_state = state;
    }

    async fn on_connection_state_change(&self, state: RTCPeerConnectionState) {
        self.metrics.lock().await.peer_connection_state = state;
    }

    async fn on_ice_candidate(&self, event: webrtc::peer_connection::RTCPeerConnectionIceEvent) {
        match event.candidate.to_json() {
            Ok(init) => {
                self.candidates.lock().await.push(WebRtcIceCandidate {
                    candidate: init.candidate,
                    sdp_mid: init.sdp_mid,
                    sdp_mline_index: init.sdp_mline_index,
                    username_fragment: init.username_fragment,
                });
                self.metrics.lock().await.local_candidates_gathered += 1;
            }
            Err(_err) => {}
        }
    }
}

fn to_rtc_ice_servers(config: &IceServerConfig) -> Vec<RTCIceServer> {
    let mut servers = Vec::new();
    for endpoint in &config.stun_servers {
        servers.push(RTCIceServer {
            urls: vec![endpoint.0.clone()],
            username: String::new(),
            credential: String::new(),
        });
    }
    for server in &config.turn_servers {
        servers.push(RTCIceServer {
            urls: vec![server.endpoint.0.clone()],
            username: server.username.clone().unwrap_or_default(),
            credential: server.credential.clone().unwrap_or_default(),
        });
    }
    servers
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Endpoint, TurnServerConfig};
    use chrono::Duration as ChronoDuration;
    use tokio::time::{sleep, Duration};

    fn test_ice_config() -> Result<IceServerConfig, TransportError> {
        IceServerConfig::new(vec![Endpoint::new("stun:127.0.0.1:3478")], vec![])
    }

    fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
        haystack
            .windows(needle.len())
            .any(|window| window == needle)
    }

    #[tokio::test]
    async fn generates_offer_answer_and_accepts_candidates_without_selecting_transport_route(
    ) -> Result<(), TransportError> {
        let offerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let answerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;

        let offer = offerer.create_offer().await?;
        assert_eq!(offer.sdp_type, WebRtcSdpType::Offer);
        assert!(offer.sdp.contains("v=0"));
        assert!(offer.sdp.contains("m=application"));

        let answer = answerer.create_answer(offer).await?;
        assert_eq!(answer.sdp_type, WebRtcSdpType::Answer);
        assert!(answer.sdp.contains("v=0"));

        offerer.accept_answer(answer).await?;
        sleep(Duration::from_millis(100)).await;
        for candidate in offerer.drain_local_candidates().await {
            answerer.add_remote_candidate(candidate).await?;
        }
        for candidate in answerer.drain_local_candidates().await {
            offerer.add_remote_candidate(candidate).await?;
        }

        offerer.close().await?;
        answerer.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn direct_path_metrics_promote_transport_session_when_webrtc_connects(
    ) -> Result<(), TransportError> {
        let offerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let answerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let offer = offerer.create_offer().await?;
        let answer = answerer.create_answer(offer).await?;
        offerer.accept_answer(answer).await?;

        let mut direct_ready = false;
        for _attempt in 0..40 {
            for candidate in offerer.drain_local_candidates().await {
                answerer.add_remote_candidate(candidate).await?;
            }
            for candidate in answerer.drain_local_candidates().await {
                offerer.add_remote_candidate(candidate).await?;
            }
            let offer_metrics = offerer.direct_path_metrics().await;
            let answer_metrics = answerer.direct_path_metrics().await;
            if offer_metrics.direct_path_ready && answer_metrics.direct_path_ready {
                direct_ready = true;
                break;
            }
            sleep(Duration::from_millis(50)).await;
        }
        assert!(
            direct_ready,
            "loopback WebRTC peers did not report direct path readiness: offer={:?} answer={:?}",
            offerer.direct_path_metrics().await,
            answerer.direct_path_metrics().await
        );

        let mut session = TransportSession::new();
        session.begin_signaling()?;
        session.begin_ice_gathering()?;
        session.begin_checking()?;
        let snapshot = offerer
            .select_direct_route_if_ready(&mut session, Endpoint::new("webrtc-direct:loopback"))
            .await?
            .ok_or_else(|| TransportError::Unavailable("direct path was not ready".to_owned()))?;
        assert_eq!(snapshot.state, crate::TransportSessionState::Direct);
        assert!(snapshot.connected());
        assert_eq!(
            snapshot
                .route
                .as_ref()
                .map(|route| route.endpoint.0.as_str()),
            Some("webrtc-direct:loopback")
        );
        assert!(
            offerer
                .direct_path_metrics()
                .await
                .remote_candidates_applied
                > 0
        );

        offerer.close().await?;
        answerer.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn sealer_round_trips_descriptions_without_visible_sdp_or_candidates(
    ) -> Result<(), TransportError> {
        let negotiator =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let offer = negotiator.create_offer().await?;
        let sealer = WebRtcNegotiationSealer::new([0x42; 32]);
        let sealed = sealer.seal_description(&offer)?;
        let opaque = sealed.to_opaque_bytes()?;
        assert!(!contains_bytes(&opaque, b"v=0"));
        assert!(!contains_bytes(&opaque, b"ice-ufrag"));
        assert!(!contains_bytes(&opaque, b"fingerprint"));
        let decoded = SealedWebRtcNegotiationPayload::from_opaque_bytes(&opaque)?;
        let opened = sealer.open_description(&decoded)?;
        assert_eq!(opened, offer);
        negotiator.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn offer_generation_rejects_expired_turn_credentials_and_redacts_debug(
    ) -> Result<(), TransportError> {
        let expired = Utc::now() - ChronoDuration::minutes(5);
        let config = IceServerConfig::new(
            vec![Endpoint::new("stun:127.0.0.1:3478")],
            vec![TurnServerConfig::new(
                Endpoint::new("turn:turn.example.invalid:3478"),
                Some("turn-user".to_owned()),
                Some("turn-secret".to_owned()),
                Some(expired.to_rfc3339()),
            )],
        )?;

        let Err(err) = WebRtcNegotiator::new(WebRtcNegotiationConfig::new(config)).await else {
            return Err(TransportError::Unavailable(
                "expired TURN credentials must fail before offer generation".to_owned(),
            ));
        };
        assert!(err.to_string().contains("TURN credential expired"));

        let candidate = WebRtcIceCandidate {
            candidate: "candidate:secret-host 1 udp 1 127.0.0.1 123 typ host".to_owned(),
            sdp_mid: Some("data".to_owned()),
            sdp_mline_index: Some(0),
            username_fragment: Some("ufrag-secret".to_owned()),
        };
        let debug = format!("{candidate:?}");
        assert!(!debug.contains("secret-host"));
        assert!(!debug.contains("ufrag-secret"));
        Ok(())
    }
}
