//! WebRTC offer/answer and ICE candidate negotiation primitives.
//!
//! This module stops at SDP/candidate generation and application. It does not
//! claim that a direct ICE route, data channel, relay, or media plane is active;
//! later Phase-G/J goals select routes and move application text/audio frames.

use crate::{
    Endpoint, IceServerConfig, TransportError, TransportSession, TransportSessionSnapshot,
};
use async_trait::async_trait;
use bytes::BytesMut;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::sync::Arc;
use tokio::sync::{mpsc, Mutex, Notify};
use tokio::time::{timeout, Duration};
use webrtc::data_channel::{DataChannel, DataChannelEvent, RTCDataChannelState};
use webrtc::peer_connection::{
    register_default_interceptors, MediaEngine, PeerConnection, PeerConnectionBuilder,
    PeerConnectionEventHandler, RTCConfigurationBuilder, RTCIceCandidateInit,
    RTCIceConnectionState, RTCIceGatheringState, RTCIceServer, RTCPeerConnectionState, RTCSdpType,
    RTCSessionDescription, Registry,
};

/// SDP type carried through signaling.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebRtcSdpType {
    /// SDP offer.
    Offer,
    /// SDP answer.
    Answer,
}

/// Serializable WebRTC session description for opaque signaling payloads.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcSessionDescription {
    /// Offer or answer.
    pub sdp_type: WebRtcSdpType,
    /// SDP body generated by the WebRTC stack.
    pub sdp: String,
}

impl fmt::Debug for WebRtcSessionDescription {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WebRtcSessionDescription")
            .field("sdp_type", &self.sdp_type)
            .field("sdp", &"<redacted>")
            .finish()
    }
}

/// Serializable ICE candidate for trickle signaling.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcIceCandidate {
    /// Candidate attribute line.
    pub candidate: String,
    /// SDP media id, when supplied by the WebRTC stack.
    #[serde(default)]
    pub sdp_mid: Option<String>,
    /// SDP media line index, when supplied by the WebRTC stack.
    #[serde(default)]
    pub sdp_mline_index: Option<u16>,
    /// ICE username fragment, when supplied by the WebRTC stack.
    #[serde(default)]
    pub username_fragment: Option<String>,
    /// Candidate source URL, when supplied by the WebRTC stack.
    #[serde(default)]
    pub url: Option<String>,
}

impl fmt::Debug for WebRtcIceCandidate {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WebRtcIceCandidate")
            .field("candidate", &"<redacted>")
            .field("sdp_mid", &self.sdp_mid)
            .field("sdp_mline_index", &self.sdp_mline_index)
            .field(
                "username_fragment",
                &self.username_fragment.as_ref().map(|_| "<redacted>"),
            )
            .field("url", &self.url.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

impl WebRtcIceCandidate {
    /// True when the candidate is relay/TURN-derived according to WebRTC candidate metadata.
    #[must_use]
    pub fn is_turn_relay_candidate(&self) -> bool {
        self.candidate
            .split_whitespace()
            .collect::<Vec<_>>()
            .windows(2)
            .any(|pair| pair == ["typ", "relay"])
            || self
                .url
                .as_deref()
                .is_some_and(|url| url.starts_with("turn:") || url.starts_with("turns:"))
    }
}

/// Encrypted negotiation payload kind carried as opaque signaling bytes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebRtcNegotiationPayloadKind {
    /// Sealed SDP offer.
    Offer,
    /// Sealed SDP answer.
    Answer,
    /// Sealed trickled ICE candidate.
    Candidate,
}

/// AES-GCM sealed WebRTC negotiation payload safe to hand to the signaling service.
#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
pub struct SealedWebRtcNegotiationPayload {
    /// Wire format version.
    pub version: u8,
    /// Payload kind used as authenticated context.
    pub kind: WebRtcNegotiationPayloadKind,
    /// 96-bit AES-GCM nonce.
    pub nonce: [u8; 12],
    /// Ciphertext plus authentication tag.
    pub ciphertext: Vec<u8>,
}

impl fmt::Debug for SealedWebRtcNegotiationPayload {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SealedWebRtcNegotiationPayload")
            .field("version", &self.version)
            .field("kind", &self.kind)
            .field("nonce", &"<redacted>")
            .field(
                "ciphertext",
                &format_args!("{} bytes", self.ciphertext.len()),
            )
            .finish()
    }
}

impl SealedWebRtcNegotiationPayload {
    /// Serialize sealed payload bytes for `SignalingClient::publish_signal`.
    pub fn to_opaque_bytes(&self) -> Result<Vec<u8>, TransportError> {
        serde_json::to_vec(self).map_err(|err| {
            TransportError::Unavailable(format!("encode sealed negotiation payload failed: {err}"))
        })
    }

    /// Decode sealed payload bytes returned by `SignalingClient::take_signals`.
    pub fn from_opaque_bytes(bytes: &[u8]) -> Result<Self, TransportError> {
        serde_json::from_slice(bytes).map_err(|err| {
            TransportError::Unavailable(format!("decode sealed negotiation payload failed: {err}"))
        })
    }
}

/// Symmetric sealer for WebRTC negotiation payloads before they enter signaling.
pub struct WebRtcNegotiationSealer {
    key: [u8; 32],
}

impl fmt::Debug for WebRtcNegotiationSealer {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WebRtcNegotiationSealer")
            .field("key", &"<redacted>")
            .finish()
    }
}

impl WebRtcNegotiationSealer {
    /// Construct a sealer from a caller-supplied 256-bit room/session negotiation key.
    #[must_use]
    pub fn new(key: [u8; 32]) -> Self {
        Self { key }
    }

    /// Seal an SDP offer or answer.
    pub fn seal_description(
        &self,
        description: &WebRtcSessionDescription,
    ) -> Result<SealedWebRtcNegotiationPayload, TransportError> {
        let kind = match description.sdp_type {
            WebRtcSdpType::Offer => WebRtcNegotiationPayloadKind::Offer,
            WebRtcSdpType::Answer => WebRtcNegotiationPayloadKind::Answer,
        };
        self.seal_json(kind, description)
    }

    /// Open a sealed SDP offer or answer.
    pub fn open_description(
        &self,
        sealed: &SealedWebRtcNegotiationPayload,
    ) -> Result<WebRtcSessionDescription, TransportError> {
        match sealed.kind {
            WebRtcNegotiationPayloadKind::Offer | WebRtcNegotiationPayloadKind::Answer => {
                self.open_json(sealed)
            }
            WebRtcNegotiationPayloadKind::Candidate => Err(TransportError::Unavailable(
                "sealed candidate cannot be opened as SDP".to_owned(),
            )),
        }
    }

    /// Seal one trickled ICE candidate.
    pub fn seal_candidate(
        &self,
        candidate: &WebRtcIceCandidate,
    ) -> Result<SealedWebRtcNegotiationPayload, TransportError> {
        self.seal_json(WebRtcNegotiationPayloadKind::Candidate, candidate)
    }

    /// Open one sealed trickled ICE candidate.
    pub fn open_candidate(
        &self,
        sealed: &SealedWebRtcNegotiationPayload,
    ) -> Result<WebRtcIceCandidate, TransportError> {
        if sealed.kind != WebRtcNegotiationPayloadKind::Candidate {
            return Err(TransportError::Unavailable(
                "sealed SDP cannot be opened as candidate".to_owned(),
            ));
        }
        self.open_json(sealed)
    }

    fn seal_json<T: Serialize>(
        &self,
        kind: WebRtcNegotiationPayloadKind,
        value: &T,
    ) -> Result<SealedWebRtcNegotiationPayload, TransportError> {
        use aes_gcm::aead::{Aead, Payload};
        use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
        use rand::RngCore;

        let mut nonce = [0u8; 12];
        rand::rngs::OsRng.fill_bytes(&mut nonce);
        let plaintext = serde_json::to_vec(value).map_err(|err| {
            TransportError::Unavailable(format!("encode negotiation payload failed: {err}"))
        })?;
        let cipher = Aes256Gcm::new_from_slice(&self.key).map_err(|err| {
            TransportError::Unavailable(format!("initialize negotiation sealer failed: {err}"))
        })?;
        let ciphertext = cipher
            .encrypt(
                Nonce::from_slice(&nonce),
                Payload {
                    msg: &plaintext,
                    aad: aad_for_kind(kind).as_bytes(),
                },
            )
            .map_err(|err| {
                TransportError::Unavailable(format!("seal negotiation payload failed: {err}"))
            })?;
        Ok(SealedWebRtcNegotiationPayload {
            version: 1,
            kind,
            nonce,
            ciphertext,
        })
    }

    fn open_json<T: for<'de> Deserialize<'de>>(
        &self,
        sealed: &SealedWebRtcNegotiationPayload,
    ) -> Result<T, TransportError> {
        use aes_gcm::aead::{Aead, Payload};
        use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
        if sealed.version != 1 {
            return Err(TransportError::Unavailable(
                "unsupported sealed negotiation payload version".to_owned(),
            ));
        }
        let cipher = Aes256Gcm::new_from_slice(&self.key).map_err(|err| {
            TransportError::Unavailable(format!("initialize negotiation opener failed: {err}"))
        })?;
        let plaintext = cipher
            .decrypt(
                Nonce::from_slice(&sealed.nonce),
                Payload {
                    msg: &sealed.ciphertext,
                    aad: aad_for_kind(sealed.kind).as_bytes(),
                },
            )
            .map_err(|err| {
                TransportError::Unavailable(format!("open negotiation payload failed: {err}"))
            })?;
        serde_json::from_slice(&plaintext).map_err(|err| {
            TransportError::Unavailable(format!("decode negotiation payload failed: {err}"))
        })
    }
}

fn aad_for_kind(kind: WebRtcNegotiationPayloadKind) -> &'static str {
    match kind {
        WebRtcNegotiationPayloadKind::Offer => "discrypt-webrtc-negotiation-v1:offer",
        WebRtcNegotiationPayloadKind::Answer => "discrypt-webrtc-negotiation-v1:answer",
        WebRtcNegotiationPayloadKind::Candidate => "discrypt-webrtc-negotiation-v1:candidate",
    }
}

/// App-facing text/control data transport over an established encrypted WebRTC DataChannel.
#[async_trait]
pub trait TextControlDataTransport: Send + Sync {
    /// Send one already-protected text/control frame as opaque bytes.
    async fn send_text_control_frame(&self, frame: Vec<u8>) -> Result<(), TransportError>;

    /// Receive the next opaque text/control frame.
    async fn recv_text_control_frame(&self) -> Result<Vec<u8>, TransportError>;

    /// Return current DataChannel transport metrics for UI/service state.
    async fn text_control_transport_metrics(&self) -> WebRtcDataTransportMetrics;
}

/// DataChannel transport metrics visible to app-service adapters.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcDataTransportMetrics {
    /// Snapshot schema version for app-service/Tauri consumers.
    pub schema_version: u16,
    /// Configured channel label.
    pub label: String,
    /// Number of currently attached WebRTC DataChannel handles.
    pub attached_channels: u64,
    /// Whether at least one DataChannel has reached the open state.
    pub open: bool,
    /// Total opaque frames sent by the app-facing data transport.
    pub frames_sent: u64,
    /// Total opaque frames received by the app-facing data transport.
    pub frames_received: u64,
    /// Total opaque bytes sent by the app-facing data transport.
    pub bytes_sent: u64,
    /// Total opaque bytes received by the app-facing data transport.
    pub bytes_received: u64,
    /// Last DataChannel state/event observed.
    pub last_state: String,
}

impl WebRtcDataTransportMetrics {
    /// Current metrics schema.
    pub const SCHEMA_VERSION: u16 = 1;
}

#[derive(Clone, Debug)]
struct DataTransportMetricsState {
    label: String,
    attached_channels: u64,
    open: bool,
    frames_sent: u64,
    frames_received: u64,
    bytes_sent: u64,
    bytes_received: u64,
    last_state: String,
}

impl DataTransportMetricsState {
    fn new(label: String) -> Self {
        Self {
            label,
            attached_channels: 0,
            open: false,
            frames_sent: 0,
            frames_received: 0,
            bytes_sent: 0,
            bytes_received: 0,
            last_state: "new".to_owned(),
        }
    }

    fn snapshot(&self) -> WebRtcDataTransportMetrics {
        WebRtcDataTransportMetrics {
            schema_version: WebRtcDataTransportMetrics::SCHEMA_VERSION,
            label: self.label.clone(),
            attached_channels: self.attached_channels,
            open: self.open,
            frames_sent: self.frames_sent,
            frames_received: self.frames_received,
            bytes_sent: self.bytes_sent,
            bytes_received: self.bytes_received,
            last_state: self.last_state.clone(),
        }
    }
}

#[derive(Clone)]
struct DataChannelHub {
    label: String,
    channels: Arc<Mutex<Vec<Arc<dyn DataChannel>>>>,
    inbound_tx: mpsc::Sender<Vec<u8>>,
    inbound_rx: Arc<Mutex<mpsc::Receiver<Vec<u8>>>>,
    metrics: Arc<Mutex<DataTransportMetricsState>>,
    open_notify: Arc<Notify>,
}

impl DataChannelHub {
    fn new(label: String) -> Self {
        let (inbound_tx, inbound_rx) = mpsc::channel(256);
        Self {
            metrics: Arc::new(Mutex::new(DataTransportMetricsState::new(label.clone()))),
            label,
            channels: Arc::new(Mutex::new(Vec::new())),
            inbound_tx,
            inbound_rx: Arc::new(Mutex::new(inbound_rx)),
            open_notify: Arc::new(Notify::new()),
        }
    }

    async fn attach(&self, channel: Arc<dyn DataChannel>) {
        let label = channel.label().await.unwrap_or_else(|_| self.label.clone());
        if label != self.label {
            return;
        }
        {
            let mut channels = self.channels.lock().await;
            channels.push(Arc::clone(&channel));
            let mut metrics = self.metrics.lock().await;
            metrics.attached_channels = channels.len() as u64;
            metrics.last_state = "attached".to_owned();
        }
        let inbound_tx = self.inbound_tx.clone();
        let metrics = Arc::clone(&self.metrics);
        let open_notify = Arc::clone(&self.open_notify);
        tokio::spawn(async move {
            while let Some(event) = channel.poll().await {
                match event {
                    DataChannelEvent::OnOpen => {
                        let mut metrics = metrics.lock().await;
                        metrics.open = true;
                        metrics.last_state = "open".to_owned();
                        drop(metrics);
                        open_notify.notify_waiters();
                    }
                    DataChannelEvent::OnMessage(message) => {
                        let bytes = message.data.to_vec();
                        {
                            let mut metrics = metrics.lock().await;
                            metrics.frames_received = metrics.frames_received.saturating_add(1);
                            metrics.bytes_received =
                                metrics.bytes_received.saturating_add(bytes.len() as u64);
                            metrics.last_state = "message".to_owned();
                        }
                        if inbound_tx.send(bytes).await.is_err() {
                            break;
                        }
                    }
                    DataChannelEvent::OnClose => {
                        let mut metrics = metrics.lock().await;
                        metrics.open = false;
                        metrics.last_state = "closed".to_owned();
                        break;
                    }
                    DataChannelEvent::OnClosing => {
                        metrics.lock().await.last_state = "closing".to_owned();
                    }
                    DataChannelEvent::OnError => {
                        metrics.lock().await.last_state = "error".to_owned();
                    }
                    DataChannelEvent::OnBufferedAmountLow => {
                        metrics.lock().await.last_state = "buffered_amount_low".to_owned();
                    }
                    DataChannelEvent::OnBufferedAmountHigh => {
                        metrics.lock().await.last_state = "buffered_amount_high".to_owned();
                    }
                }
            }
        });
    }

    async fn wait_open(&self, duration: Duration) -> Result<(), TransportError> {
        if self.metrics.lock().await.open {
            return Ok(());
        }
        timeout(duration, self.open_notify.notified())
            .await
            .map_err(|_| TransportError::Unavailable("DataChannel did not open".to_owned()))?;
        Ok(())
    }

    async fn send(&self, frame: Vec<u8>) -> Result<(), TransportError> {
        if frame.is_empty() {
            return Err(TransportError::Unavailable(
                "text/control data frame is empty".to_owned(),
            ));
        }
        self.wait_open(Duration::from_secs(10)).await?;
        let channels = self.channels.lock().await;
        let channel = channels
            .first()
            .cloned()
            .ok_or_else(|| TransportError::Unavailable("no DataChannel attached".to_owned()))?;
        drop(channels);
        if channel.ready_state().await.map_err(data_channel_error)? != RTCDataChannelState::Open {
            return Err(TransportError::Unavailable(
                "DataChannel is not open".to_owned(),
            ));
        }
        let sent_len = frame.len();
        channel
            .send(BytesMut::from(frame.as_slice()))
            .await
            .map_err(data_channel_error)?;
        let mut metrics = self.metrics.lock().await;
        metrics.frames_sent = metrics.frames_sent.saturating_add(1);
        metrics.bytes_sent = metrics.bytes_sent.saturating_add(sent_len as u64);
        metrics.last_state = "sent".to_owned();
        Ok(())
    }

    async fn recv(&self) -> Result<Vec<u8>, TransportError> {
        let mut inbound_rx = self.inbound_rx.lock().await;
        inbound_rx
            .recv()
            .await
            .ok_or_else(|| TransportError::Unavailable("DataChannel receive closed".to_owned()))
    }

    async fn snapshot(&self) -> WebRtcDataTransportMetrics {
        self.metrics.lock().await.snapshot()
    }
}

fn data_channel_error(error: impl fmt::Display) -> TransportError {
    TransportError::Unavailable(format!("WebRTC DataChannel failed: {error}"))
}

/// Direct ICE/WebRTC state and metrics visible to app-service adapters.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcDirectPathMetrics {
    /// Snapshot schema version for app-service/Tauri consumers.
    pub schema_version: u16,
    /// Current aggregate peer connection state.
    pub peer_connection_state: String,
    /// Current ICE connection state.
    pub ice_connection_state: String,
    /// Current ICE gathering state.
    pub ice_gathering_state: String,
    /// Total local candidates gathered by the WebRTC stack.
    pub local_candidates_gathered: u64,
    /// Total remote trickle candidates applied to this peer.
    pub remote_candidates_applied: u64,
    /// Configured TURN server count for fallback path availability.
    pub configured_turn_servers: u64,
    /// Locally gathered relay/TURN candidates.
    pub local_relay_candidates_gathered: u64,
    /// Remote relay/TURN candidates applied through trickle ICE.
    pub remote_relay_candidates_applied: u64,
    /// True only when WebRTC reports a direct ICE-capable connected/completed state.
    pub direct_path_ready: bool,
    /// True only when WebRTC is connected and relay candidate evidence exists with TURN configured.
    pub turn_fallback_ready: bool,
}

impl WebRtcDirectPathMetrics {
    /// Current metrics schema.
    pub const SCHEMA_VERSION: u16 = 1;
}

#[derive(Clone, Debug)]
struct DirectPathMetricsState {
    peer_connection_state: RTCPeerConnectionState,
    ice_connection_state: RTCIceConnectionState,
    ice_gathering_state: RTCIceGatheringState,
    local_candidates_gathered: u64,
    remote_candidates_applied: u64,
    configured_turn_servers: u64,
    local_relay_candidates_gathered: u64,
    remote_relay_candidates_applied: u64,
}

impl Default for DirectPathMetricsState {
    fn default() -> Self {
        Self {
            peer_connection_state: RTCPeerConnectionState::New,
            ice_connection_state: RTCIceConnectionState::New,
            ice_gathering_state: RTCIceGatheringState::New,
            local_candidates_gathered: 0,
            remote_candidates_applied: 0,
            configured_turn_servers: 0,
            local_relay_candidates_gathered: 0,
            remote_relay_candidates_applied: 0,
        }
    }
}

impl DirectPathMetricsState {
    fn with_configured_turn_servers(configured_turn_servers: u64) -> Self {
        Self {
            configured_turn_servers,
            ..Self::default()
        }
    }

    fn snapshot(&self) -> WebRtcDirectPathMetrics {
        let connected = matches!(
            self.peer_connection_state,
            RTCPeerConnectionState::Connected
        ) || matches!(
            self.ice_connection_state,
            RTCIceConnectionState::Connected | RTCIceConnectionState::Completed
        );
        WebRtcDirectPathMetrics {
            schema_version: WebRtcDirectPathMetrics::SCHEMA_VERSION,
            peer_connection_state: self.peer_connection_state.to_string(),
            ice_connection_state: self.ice_connection_state.to_string(),
            ice_gathering_state: self.ice_gathering_state.to_string(),
            local_candidates_gathered: self.local_candidates_gathered,
            remote_candidates_applied: self.remote_candidates_applied,
            configured_turn_servers: self.configured_turn_servers,
            local_relay_candidates_gathered: self.local_relay_candidates_gathered,
            remote_relay_candidates_applied: self.remote_relay_candidates_applied,
            direct_path_ready: connected,
            turn_fallback_ready: connected
                && self.configured_turn_servers > 0
                && (self.local_relay_candidates_gathered > 0
                    || self.remote_relay_candidates_applied > 0),
        }
    }
}

/// Local WebRTC negotiation configuration.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebRtcNegotiationConfig {
    /// Validated STUN/TURN configuration from invite/group policy.
    pub ice_servers: IceServerConfig,
    /// Local UDP bind addresses. Use `127.0.0.1:0` in deterministic tests.
    pub udp_addrs: Vec<String>,
    /// DataChannel label used to ensure SDP negotiates an application m-line.
    pub data_channel_label: String,
}

impl WebRtcNegotiationConfig {
    /// Build a config with a safe loopback bind default for tests/local embedded use.
    #[must_use]
    pub fn new(ice_servers: IceServerConfig) -> Self {
        Self {
            ice_servers,
            udp_addrs: vec!["127.0.0.1:0".to_owned()],
            data_channel_label: "discrypt-control".to_owned(),
        }
    }

    fn validate(&self, now: DateTime<Utc>) -> Result<(), TransportError> {
        self.ice_servers.validate_credentials_at(now)?;
        if self.udp_addrs.is_empty() {
            return Err(TransportError::Unavailable(
                "at least one UDP bind address is required for WebRTC negotiation".to_owned(),
            ));
        }
        if self.data_channel_label.trim().is_empty() {
            return Err(TransportError::Unavailable(
                "data channel label is required for WebRTC negotiation".to_owned(),
            ));
        }
        Ok(())
    }
}

/// WebRTC negotiation owner for one peer connection.
pub struct WebRtcNegotiator {
    peer_connection: Box<dyn PeerConnection>,
    candidates: Arc<Mutex<Vec<WebRtcIceCandidate>>>,
    metrics: Arc<Mutex<DirectPathMetricsState>>,
    data_channels: DataChannelHub,
    data_channel_label: String,
    turn_endpoints: Vec<Endpoint>,
}

impl WebRtcNegotiator {
    /// Create a WebRTC peer connection configured with validated ICE servers.
    pub async fn new(config: WebRtcNegotiationConfig) -> Result<Self, TransportError> {
        config.validate(Utc::now())?;
        let candidates = Arc::new(Mutex::new(Vec::new()));
        let metrics = Arc::new(Mutex::new(
            DirectPathMetricsState::with_configured_turn_servers(
                config.ice_servers.turn_servers.len() as u64,
            ),
        ));
        let data_channels = DataChannelHub::new(config.data_channel_label.clone());
        let handler = Arc::new(CandidateCollector {
            candidates: Arc::clone(&candidates),
            metrics: Arc::clone(&metrics),
            data_channels: data_channels.clone(),
        });
        let mut media = MediaEngine::default();
        media.register_default_codecs().map_err(|err| {
            TransportError::Unavailable(format!("register media codecs failed: {err}"))
        })?;
        let registry =
            register_default_interceptors(Registry::new(), &mut media).map_err(|err| {
                TransportError::Unavailable(format!("register WebRTC interceptors failed: {err}"))
            })?;
        let peer_connection = PeerConnectionBuilder::new()
            .with_configuration(
                RTCConfigurationBuilder::new()
                    .with_ice_servers(to_rtc_ice_servers(&config.ice_servers))
                    .build(),
            )
            .with_media_engine(media)
            .with_interceptor_registry(registry)
            .with_handler(handler)
            .with_udp_addrs(config.udp_addrs.clone())
            .build()
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("build WebRTC peer failed: {err}"))
            })?;
        Ok(Self {
            peer_connection: Box::new(peer_connection),
            candidates,
            metrics,
            data_channels,
            data_channel_label: config.data_channel_label,
            turn_endpoints: config
                .ice_servers
                .turn_servers
                .iter()
                .map(|server| server.endpoint.clone())
                .collect(),
        })
    }

    /// Create and set a local SDP offer. Candidate gathering starts after this call.
    pub async fn create_offer(&self) -> Result<WebRtcSessionDescription, TransportError> {
        let _channel = self
            .peer_connection
            .create_data_channel(&self.data_channel_label, None)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("create data channel failed: {err}"))
            })?;
        self.data_channels.attach(_channel).await;
        let offer = self
            .peer_connection
            .create_offer(None)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("create WebRTC offer failed: {err}"))
            })?;
        self.peer_connection
            .set_local_description(offer)
            .await
            .map_err(|err| TransportError::Unavailable(format!("set local offer failed: {err}")))?;
        let local = self
            .peer_connection
            .local_description()
            .await
            .ok_or_else(|| {
                TransportError::Unavailable("WebRTC local offer was not recorded".to_owned())
            })?;
        WebRtcSessionDescription::from_rtc(local)
    }

    /// Apply a remote offer, then create and set a local SDP answer.
    pub async fn create_answer(
        &self,
        remote_offer: WebRtcSessionDescription,
    ) -> Result<WebRtcSessionDescription, TransportError> {
        self.peer_connection
            .set_remote_description(remote_offer.into_rtc()?)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("set remote offer failed: {err}"))
            })?;
        let answer = self
            .peer_connection
            .create_answer(None)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("create WebRTC answer failed: {err}"))
            })?;
        self.peer_connection
            .set_local_description(answer)
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("set local answer failed: {err}"))
            })?;
        let local = self
            .peer_connection
            .local_description()
            .await
            .ok_or_else(|| {
                TransportError::Unavailable("WebRTC local answer was not recorded".to_owned())
            })?;
        WebRtcSessionDescription::from_rtc(local)
    }

    /// Apply a remote answer to an offer-side peer connection.
    pub async fn accept_answer(
        &self,
        remote_answer: WebRtcSessionDescription,
    ) -> Result<(), TransportError> {
        self.peer_connection
            .set_remote_description(remote_answer.into_rtc()?)
            .await
            .map_err(|err| TransportError::Unavailable(format!("set remote answer failed: {err}")))
    }

    /// Apply one trickled remote ICE candidate.
    pub async fn add_remote_candidate(
        &self,
        candidate: WebRtcIceCandidate,
    ) -> Result<(), TransportError> {
        if candidate.is_turn_relay_candidate() {
            self.metrics.lock().await.remote_relay_candidates_applied += 1;
        }
        self.peer_connection
            .add_ice_candidate(candidate.into_rtc())
            .await
            .map_err(|err| {
                TransportError::Unavailable(format!("add ICE candidate failed: {err}"))
            })?;
        self.metrics.lock().await.remote_candidates_applied += 1;
        Ok(())
    }

    /// Drain locally gathered ICE candidates in callback order for signaling.
    pub async fn drain_local_candidates(&self) -> Vec<WebRtcIceCandidate> {
        let mut candidates = self.candidates.lock().await;
        std::mem::take(&mut *candidates)
    }

    /// Current direct ICE/WebRTC metrics for app-service/Tauri state surfaces.
    pub async fn direct_path_metrics(&self) -> WebRtcDirectPathMetrics {
        self.metrics.lock().await.snapshot()
    }

    /// Select a direct route in a transport session only after WebRTC reports readiness.
    pub async fn select_direct_route_if_ready(
        &self,
        session: &mut TransportSession,
        endpoint: Endpoint,
    ) -> Result<Option<TransportSessionSnapshot>, TransportError> {
        if !self.direct_path_metrics().await.direct_path_ready {
            return Ok(None);
        }
        session
            .select_direct(endpoint)
            .map(Some)
            .map_err(Into::into)
    }

    /// Select a TURN relay route only after WebRTC reports relay candidate evidence.
    pub async fn select_turn_route_if_ready(
        &self,
        session: &mut TransportSession,
    ) -> Result<Option<TransportSessionSnapshot>, TransportError> {
        if !self.direct_path_metrics().await.turn_fallback_ready {
            return Ok(None);
        }
        let endpoint = self.turn_endpoints.first().cloned().ok_or_else(|| {
            TransportError::Unavailable("TURN fallback has no endpoint".to_owned())
        })?;
        session
            .select_turn_relay(endpoint)
            .map(Some)
            .map_err(Into::into)
    }

    /// Wait for the app-facing text/control DataChannel to open.
    pub async fn wait_text_control_transport_ready(
        &self,
        duration: Duration,
    ) -> Result<(), TransportError> {
        self.data_channels.wait_open(duration).await
    }

    /// Close the peer connection.
    pub async fn close(&self) -> Result<(), TransportError> {
        self.peer_connection
            .close()
            .await
            .map_err(|err| TransportError::Unavailable(format!("close WebRTC peer failed: {err}")))
    }
}

#[async_trait]
impl TextControlDataTransport for WebRtcNegotiator {
    async fn send_text_control_frame(&self, frame: Vec<u8>) -> Result<(), TransportError> {
        self.data_channels.send(frame).await
    }

    async fn recv_text_control_frame(&self) -> Result<Vec<u8>, TransportError> {
        self.data_channels.recv().await
    }

    async fn text_control_transport_metrics(&self) -> WebRtcDataTransportMetrics {
        self.data_channels.snapshot().await
    }
}

impl WebRtcSessionDescription {
    fn from_rtc(description: RTCSessionDescription) -> Result<Self, TransportError> {
        let sdp_type = match description.sdp_type {
            RTCSdpType::Offer => WebRtcSdpType::Offer,
            RTCSdpType::Answer => WebRtcSdpType::Answer,
            other => {
                return Err(TransportError::Unavailable(format!(
                    "unsupported SDP type for Discrypt negotiation: {other:?}"
                )));
            }
        };
        Ok(Self {
            sdp_type,
            sdp: description.sdp,
        })
    }

    fn into_rtc(self) -> Result<RTCSessionDescription, TransportError> {
        let rtc = match self.sdp_type {
            WebRtcSdpType::Offer => RTCSessionDescription::offer(self.sdp),
            WebRtcSdpType::Answer => RTCSessionDescription::answer(self.sdp),
        }
        .map_err(|err| TransportError::Unavailable(format!("parse remote SDP failed: {err}")))?;
        Ok(rtc)
    }
}

impl WebRtcIceCandidate {
    fn into_rtc(self) -> RTCIceCandidateInit {
        RTCIceCandidateInit {
            candidate: self.candidate,
            sdp_mid: self.sdp_mid,
            sdp_mline_index: self.sdp_mline_index,
            username_fragment: self.username_fragment,
            url: self.url,
        }
    }
}

#[derive(Clone)]
struct CandidateCollector {
    candidates: Arc<Mutex<Vec<WebRtcIceCandidate>>>,
    metrics: Arc<Mutex<DirectPathMetricsState>>,
    data_channels: DataChannelHub,
}

#[async_trait]
impl PeerConnectionEventHandler for CandidateCollector {
    async fn on_data_channel(&self, channel: Arc<dyn DataChannel>) {
        self.data_channels.attach(channel).await;
    }

    async fn on_ice_gathering_state_change(&self, state: RTCIceGatheringState) {
        self.metrics.lock().await.ice_gathering_state = state;
    }

    async fn on_ice_connection_state_change(&self, state: RTCIceConnectionState) {
        self.metrics.lock().await.ice_connection_state = state;
    }

    async fn on_connection_state_change(&self, state: RTCPeerConnectionState) {
        self.metrics.lock().await.peer_connection_state = state;
    }

    async fn on_ice_candidate(&self, event: webrtc::peer_connection::RTCPeerConnectionIceEvent) {
        match event.candidate.to_json() {
            Ok(init) => {
                let candidate = WebRtcIceCandidate {
                    candidate: init.candidate,
                    sdp_mid: init.sdp_mid,
                    sdp_mline_index: init.sdp_mline_index,
                    username_fragment: init.username_fragment,
                    url: init.url,
                };
                let is_relay = candidate.is_turn_relay_candidate();
                self.candidates.lock().await.push(candidate);
                let mut metrics = self.metrics.lock().await;
                metrics.local_candidates_gathered += 1;
                if is_relay {
                    metrics.local_relay_candidates_gathered += 1;
                }
            }
            Err(_err) => {}
        }
    }
}

fn to_rtc_ice_servers(config: &IceServerConfig) -> Vec<RTCIceServer> {
    let mut servers = Vec::new();
    for endpoint in &config.stun_servers {
        servers.push(RTCIceServer {
            urls: vec![endpoint.0.clone()],
            username: String::new(),
            credential: String::new(),
        });
    }
    for server in &config.turn_servers {
        servers.push(RTCIceServer {
            urls: vec![server.endpoint.0.clone()],
            username: server.username.clone().unwrap_or_default(),
            credential: server.credential.clone().unwrap_or_default(),
        });
    }
    servers
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Endpoint, TurnServerConfig};
    use chrono::Duration as ChronoDuration;
    use tokio::time::{sleep, Duration};

    fn test_ice_config() -> Result<IceServerConfig, TransportError> {
        IceServerConfig::new(vec![Endpoint::new("stun:127.0.0.1:3478")], vec![])
    }

    fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
        haystack
            .windows(needle.len())
            .any(|window| window == needle)
    }

    #[tokio::test]
    async fn generates_offer_answer_and_accepts_candidates_without_selecting_transport_route(
    ) -> Result<(), TransportError> {
        let offerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let answerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;

        let offer = offerer.create_offer().await?;
        assert_eq!(offer.sdp_type, WebRtcSdpType::Offer);
        assert!(offer.sdp.contains("v=0"));
        assert!(offer.sdp.contains("m=application"));

        let answer = answerer.create_answer(offer).await?;
        assert_eq!(answer.sdp_type, WebRtcSdpType::Answer);
        assert!(answer.sdp.contains("v=0"));

        offerer.accept_answer(answer).await?;
        sleep(Duration::from_millis(100)).await;
        for candidate in offerer.drain_local_candidates().await {
            answerer.add_remote_candidate(candidate).await?;
        }
        for candidate in answerer.drain_local_candidates().await {
            offerer.add_remote_candidate(candidate).await?;
        }

        offerer.close().await?;
        answerer.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn direct_path_metrics_promote_transport_session_when_webrtc_connects(
    ) -> Result<(), TransportError> {
        let offerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let answerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let offer = offerer.create_offer().await?;
        let answer = answerer.create_answer(offer).await?;
        offerer.accept_answer(answer).await?;

        let mut direct_ready = false;
        for _attempt in 0..40 {
            for candidate in offerer.drain_local_candidates().await {
                answerer.add_remote_candidate(candidate).await?;
            }
            for candidate in answerer.drain_local_candidates().await {
                offerer.add_remote_candidate(candidate).await?;
            }
            let offer_metrics = offerer.direct_path_metrics().await;
            let answer_metrics = answerer.direct_path_metrics().await;
            if offer_metrics.direct_path_ready && answer_metrics.direct_path_ready {
                direct_ready = true;
                break;
            }
            sleep(Duration::from_millis(50)).await;
        }
        assert!(
            direct_ready,
            "loopback WebRTC peers did not report direct path readiness: offer={:?} answer={:?}",
            offerer.direct_path_metrics().await,
            answerer.direct_path_metrics().await
        );

        let mut session = TransportSession::new();
        session.begin_signaling()?;
        session.begin_ice_gathering()?;
        session.begin_checking()?;
        let snapshot = offerer
            .select_direct_route_if_ready(&mut session, Endpoint::new("webrtc-direct:loopback"))
            .await?
            .ok_or_else(|| TransportError::Unavailable("direct path was not ready".to_owned()))?;
        assert_eq!(snapshot.state, crate::TransportSessionState::Direct);
        assert!(snapshot.connected());
        assert_eq!(
            snapshot
                .route
                .as_ref()
                .map(|route| route.endpoint.0.as_str()),
            Some("webrtc-direct:loopback")
        );
        assert!(
            offerer
                .direct_path_metrics()
                .await
                .remote_candidates_applied
                > 0
        );

        offerer.close().await?;
        answerer.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn text_control_data_transport_exchanges_opaque_frames_over_datachannel(
    ) -> Result<(), TransportError> {
        let offerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let answerer =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let offer = offerer.create_offer().await?;
        let answer = answerer.create_answer(offer).await?;
        offerer.accept_answer(answer).await?;

        let mut connected = false;
        for _attempt in 0..80 {
            for candidate in offerer.drain_local_candidates().await {
                answerer.add_remote_candidate(candidate).await?;
            }
            for candidate in answerer.drain_local_candidates().await {
                offerer.add_remote_candidate(candidate).await?;
            }
            if offerer.direct_path_metrics().await.direct_path_ready
                && answerer.direct_path_metrics().await.direct_path_ready
            {
                connected = true;
                break;
            }
            sleep(Duration::from_millis(50)).await;
        }
        assert!(connected, "WebRTC peers did not connect for data transport");
        offerer
            .wait_text_control_transport_ready(Duration::from_secs(5))
            .await?;
        answerer
            .wait_text_control_transport_ready(Duration::from_secs(5))
            .await?;

        let outbound = b"ciphertext:text-control-frame:v1".to_vec();
        offerer.send_text_control_frame(outbound.clone()).await?;
        let received =
            tokio::time::timeout(Duration::from_secs(5), answerer.recv_text_control_frame())
                .await
                .map_err(|_| {
                    TransportError::Unavailable("timed out receiving frame".to_owned())
                })??;
        assert_eq!(received, outbound);

        let ack = b"ciphertext:control-ack:v1".to_vec();
        answerer.send_text_control_frame(ack.clone()).await?;
        let received_ack =
            tokio::time::timeout(Duration::from_secs(5), offerer.recv_text_control_frame())
                .await
                .map_err(|_| TransportError::Unavailable("timed out receiving ack".to_owned()))??;
        assert_eq!(received_ack, ack);

        let offerer_metrics = offerer.text_control_transport_metrics().await;
        let answerer_metrics = answerer.text_control_transport_metrics().await;
        assert!(offerer_metrics.open);
        assert!(answerer_metrics.open);
        assert_eq!(offerer_metrics.frames_sent, 1);
        assert_eq!(offerer_metrics.frames_received, 1);
        assert_eq!(answerer_metrics.frames_sent, 1);
        assert_eq!(answerer_metrics.frames_received, 1);

        offerer.close().await?;
        answerer.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn sealer_round_trips_descriptions_without_visible_sdp_or_candidates(
    ) -> Result<(), TransportError> {
        let negotiator =
            WebRtcNegotiator::new(WebRtcNegotiationConfig::new(test_ice_config()?)).await?;
        let offer = negotiator.create_offer().await?;
        let sealer = WebRtcNegotiationSealer::new([0x42; 32]);
        let sealed = sealer.seal_description(&offer)?;
        let opaque = sealed.to_opaque_bytes()?;
        assert!(!contains_bytes(&opaque, b"v=0"));
        assert!(!contains_bytes(&opaque, b"ice-ufrag"));
        assert!(!contains_bytes(&opaque, b"fingerprint"));
        let decoded = SealedWebRtcNegotiationPayload::from_opaque_bytes(&opaque)?;
        let opened = sealer.open_description(&decoded)?;
        assert_eq!(opened, offer);
        negotiator.close().await?;
        Ok(())
    }

    #[tokio::test]
    async fn offer_generation_rejects_expired_turn_credentials_and_redacts_debug(
    ) -> Result<(), TransportError> {
        let expired = Utc::now() - ChronoDuration::minutes(5);
        let config = IceServerConfig::new(
            vec![Endpoint::new("stun:127.0.0.1:3478")],
            vec![TurnServerConfig::new(
                Endpoint::new("turn:turn.example.invalid:3478"),
                Some("turn-user".to_owned()),
                Some("turn-secret".to_owned()),
                Some(expired.to_rfc3339()),
            )],
        )?;

        let Err(err) = WebRtcNegotiator::new(WebRtcNegotiationConfig::new(config)).await else {
            return Err(TransportError::Unavailable(
                "expired TURN credentials must fail before offer generation".to_owned(),
            ));
        };
        assert!(err.to_string().contains("TURN credential expired"));

        let candidate = WebRtcIceCandidate {
            candidate: "candidate:secret-host 1 udp 1 127.0.0.1 123 typ host".to_owned(),
            sdp_mid: Some("data".to_owned()),
            sdp_mline_index: Some(0),
            username_fragment: Some("ufrag-secret".to_owned()),
            url: Some("turns:secret-turn.example.invalid:5349".to_owned()),
        };
        let debug = format!("{candidate:?}");
        assert!(!debug.contains("secret-host"));
        assert!(!debug.contains("ufrag-secret"));
        assert!(!debug.contains("secret-turn"));
        Ok(())
    }

    #[tokio::test]
    async fn turn_fallback_accepts_configured_credentials_and_requires_relay_evidence(
    ) -> Result<(), TransportError> {
        let turn_endpoint = Endpoint::new("turns:turn.example.invalid:5349");
        let config = IceServerConfig::new(
            vec![Endpoint::new("stun:127.0.0.1:3478")],
            vec![TurnServerConfig::new(
                turn_endpoint.clone(),
                Some("configured-user".to_owned()),
                Some("configured-secret".to_owned()),
                None,
            )],
        )?;
        let negotiator = WebRtcNegotiator::new(WebRtcNegotiationConfig::new(config)).await?;
        let offer = negotiator.create_offer().await?;
        assert_eq!(offer.sdp_type, WebRtcSdpType::Offer);
        assert!(
            !format!("{:?}", negotiator.direct_path_metrics().await).contains("configured-secret")
        );
        assert_eq!(
            negotiator
                .direct_path_metrics()
                .await
                .configured_turn_servers,
            1
        );

        let mut session = TransportSession::new();
        session.begin_signaling()?;
        session.begin_ice_gathering()?;
        session.begin_checking()?;
        assert!(negotiator
            .select_turn_route_if_ready(&mut session)
            .await?
            .is_none());

        {
            let mut metrics = negotiator.metrics.lock().await;
            metrics.peer_connection_state = RTCPeerConnectionState::Connected;
            metrics.remote_relay_candidates_applied = 1;
        }
        let snapshot = negotiator
            .select_turn_route_if_ready(&mut session)
            .await?
            .ok_or_else(|| TransportError::Unavailable("TURN route was not ready".to_owned()))?;
        assert_eq!(snapshot.state, crate::TransportSessionState::TurnRelay);
        assert!(snapshot.connected());
        assert_eq!(
            snapshot.route.as_ref().map(|route| route.endpoint.clone()),
            Some(turn_endpoint)
        );
        assert!(negotiator.direct_path_metrics().await.turn_fallback_ready);

        negotiator.close().await?;
        Ok(())
    }

    #[test]
    fn sealed_relay_candidate_keeps_turn_metadata_ciphertext_only() -> Result<(), TransportError> {
        let relay_candidate = WebRtcIceCandidate {
            candidate: "candidate:relay-foundation 1 udp 1677729535 203.0.113.10 5349 typ relay"
                .to_owned(),
            sdp_mid: Some("0".to_owned()),
            sdp_mline_index: Some(0),
            username_fragment: Some("relay-ufrag".to_owned()),
            url: Some("turns:turn.example.invalid:5349".to_owned()),
        };
        assert!(relay_candidate.is_turn_relay_candidate());
        let sealed = WebRtcNegotiationSealer::new([0x54; 32]).seal_candidate(&relay_candidate)?;
        let opaque = sealed.to_opaque_bytes()?;
        assert!(!contains_bytes(&opaque, b"typ relay"));
        assert!(!contains_bytes(&opaque, b"turn.example.invalid"));
        assert!(!contains_bytes(&opaque, b"relay-ufrag"));
        assert_eq!(
            WebRtcNegotiationSealer::new([0x54; 32])
                .open_candidate(&SealedWebRtcNegotiationPayload::from_opaque_bytes(&opaque)?)?,
            relay_candidate
        );
        Ok(())
    }
}
